apiVersion: v1
kind: Service
metadata:
  name: dengue-predictive-model
  labels:
    app: dengue-predictive-model
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: dengue-predictive-model
