apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-dengue
  labels:
    app: neo4j-dengue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-dengue
  template:
    metadata:
      labels:
        app: neo4j-dengue
    spec:
      containers:
      - name: neo4j
        image: image-registry.openshift-image-registry.svc:5000/dengue-kg/neo4j-dengue:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        env:
        - name: NEO4J_AUTH
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: neo4j-auth
              optional: false
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
        - name: neo4j-config
          mountPath: /var/lib/neo4j/conf/neo4j.custom.conf
          subPath: neo4j.custom.conf
        livenessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 7474
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-data-pvc
      - name: neo4j-logs
        emptyDir: {}
      - name: neo4j-config
        configMap:
          name: neo4j-config
      securityContext:
        fsGroup: 7474
