apiVersion: v1
kind: Service
metadata:
  name: neo4j-dengue
  labels:
    app: neo4j-dengue
spec:
  ports:
  - port: 7474
    name: http
    targetPort: 7474
  - port: 7687
    name: bolt
    targetPort: 7687
  selector:
    app: neo4j-dengue
