apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - configmap.yaml

commonLabels:
  app: dengue-frontend
  part-of: dengue-knowledge-graph
  component: frontend
