apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-dengue-data
  labels:
    app: dengue-kg
    component: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Adjust size as needed
